### ISSUE TITLE
Data Races detected in the generated kernel

### ISSUE THREAD

**Issue by PeimingLiu** [nullplay/Unified-Convolution-Framework#1]
Data races are detected in the generated kernel in `submanifold_cpu.c`.

```
==================
WARNING: ThreadSanitizer: data race (pid=2836891)
  Read of size 4 at 0x7fe141874324 by main thread:
    #0 compute._omp_fn.1 <null> (submanifold_cpu.so+0x1c15)
    #1 GOMP_parallel_loop_nonmonotonic_runtime <null> (libgomp.so.1+0x10f38)
    #2 main /usr/local/google/home/peiming/projects/Unified-Convolution-Framework/benchmark/submanifold_sparse_convolution/cpu/3dcpu.cpp:212 (3dcpu+0xe38c)

  Previous write of size 4 at 0x7fe141874324 by thread T96:
    [failed to restore the stack]

  Location is heap block of size 33554432 at 0x7fe14042a000 allocated by main thread:
    #0 realloc ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:680 (libtsan.so.2+0x4302f)
    #1 pack <null> (5x1096hkmtw4.so+0x19e4)
    #2 __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58 (libc.so.6+0x27189)

  Thread T96 (tid=2837008, running) created by main thread at:
    #0 pthread_create ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1001 (libtsan.so.2+0x5e686)
    #1 <null> <null> (libgomp.so.1+0x1d38f)
    #2 main /usr/local/google/home/peiming/projects/Unified-Convolution-Framework/benchmark/submanifold_sparse_convolution/cpu/3dcpu.cpp:212 (3dcpu+0xe38c)
```

I do not think you can parallelize the outermost loop without proper synchronization when there are multiple reduction loops nested in.

To reproduce:
add `-fsanitize=thread` to both Makefile and the `gcc_command` defined in 3dcpu.c

**Comment by nullplay** [comment]
Hi @PeimingLiu ,

Thank you for your interest. While I am not an expert in thread sanitizer, according to my Google search, there can be false positives with OpenMP. However, I was unable to reproduce the result as a compiled program with `-fsanitize=thread` crashes in my environment. Upon examining the generated submanifold convolution code (`./code/submanifold_cpu.c`), I do not think there can be a data race, as UCF is parallelizing the loop index that corresponds to an independent output region.

One way to address this issue is to compare your output with the reference. To do this, you can add the following code snippet at `3dcpu.cpp:221` to write the output to a file:
```c++
// add this to 3dcpu.cpp:221
int* O2_pos = (int*)(O.getTacoTensorT()->indices[1][0]);
int* O3_pos = (int*)(O.getTacoTensorT()->indices[2][0]);
int O4_dimension = (int)(O.getTacoTensorT()->dimensions[3]);
float* val = (float*)(O.getTacoTensorT()->vals);
ofstream File ("out.txt");
for (int i =0; i<O3_pos[O2_pos[O4_dimension]]*O4_dimension; i++) {
  File << val[i] << endl;
}
```

After running `make` without sanitizer, execute `./3dcpu ../../Dataset/3D/office.tns dense 0 RSTCM`. You can then check if `out.txt` is the same as `ref.txt` by running `diff out.txt ref.txt`.
Download `ref.txt` at here : [ref.txt](https://github.com/nullplay/Unified-Convolution-Framework/files/11310118/ref.txt)

If diff reports that they are different, can you please show us the `./code/submanifold_cpu.c` file?

**Comment by PeimingLiu** [comment]
Thanks for the reply!

I didn’t not check the output (but I assume we are having the same kernel because I did not change your code)

The reason why I had the concern is that it is generating a sparse output (is it?) and inserting into a sparse output is not an atomic operation (Even it is synchronized, it might result in unordered level that is inefficient to process later without additional sorting).

maybe it is because you exploit the fact that the output has the same sparsity pattern as the filter tensor. But it is not a general optimization that you can apply on other convolution kernels, right?

**Comment by nullplay** [comment]
Great point and Yes for both of your questions. 

```
// (p,q) : Output's Width and Height
// (m,c) : out channel and in channel
// (r,s) : Filter Width and Height
Out(p,q,m) = Mask(p,q) * (In(p+r,q+s,c) * Filter(r,s,c,m)) # 2D Submanifold
```
For submanifold sparse convolution, we are generating a sparse output. However, we are using a very special optimization by levaraging the fact that the spatial sparsity pattern of output and mask are identical. When you look at the above expression, we can observe that `Mask(p,q)` controls the output's spatial sparsity pattern (`Out(p,q,:)`). 

As you pointed out, this kind of optimization is not generally applicable unless output sparsity pattern is statically predictable.

**Comment by PeimingLiu** [comment]
An totally irrelevant comment ;-)

I saw some benchmark on sparse-filter convolution, just FYI, it was supported in MLIR sparse compiler two years ago( https://reviews.llvm.org/D109783).
